version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/dmathieu/dice
    steps:
      - checkout
      - run:
          name: Download cc-test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: make ci
      - run:
          name: Upload coverage to CircleCI
          command: ./cc-test-reporter after-build --exit-code $?
  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/dmathieu/dice
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Log into Docker Hub
          command: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run:
          name: Compile and release
          command: bin/release
workflows:
  version: 2
  build-release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
