version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/dmathieu/dice
    steps:
      - checkout
      - run:
          name: Run tests
          command: make ci
