---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dice
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dice
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["watch", "list", "get", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["watch", "list", "get"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dice
subjects:
  - kind: ServiceAccount
    name: dice
    namespace: kube-system
---
apiVersion: batch/v1
kind: Deployment
metadata:
  name: dice
  namespace: kube-system
spec:
  replicas: 2
  template:
    spec:
      serviceAccountName: dice
      containers:
      - name: dice
        image: docker.io/dmathieu/dice-linux-amd64
        command:
          - ./dice
          - loop
          - -c=aws
        env:
          - name: AWS_REGION
            value: us-east-1
